-- MySQL Script generated by MySQL Workbench
-- sob 12 dec 2020 20:05:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovenian_ci ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`address` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `houseNumber` INT NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`admin` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`book` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_slovenian_ci' NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_slovenian_ci' NOT NULL,
  `price` FLOAT NOT NULL DEFAULT '0',
  `year` INT NOT NULL,
  `activeBook` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`customer` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `address_idAddress` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_customer_address_idx` (`address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_idAddress`)
    REFERENCES `bookstore`.`address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`seller` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`seller` (
  `idSeller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
    
  PRIMARY KEY (`idSeller`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;

ALTER TABLE book ADD FULLTEXT(title);
-- -----------------------------------------------------
-- Table `bookstore`.`finalorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`finalorder` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`finalorder` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL,
  `total` FLOAT NOT NULL,
  `customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_finalorder_customer1_idx` (`customer_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_finalorder_customer1`
    FOREIGN KEY (`customer_idCustomer`)
    REFERENCES `bookstore`.`customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `bookstore`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`orders` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`orders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `finalorder_orderID` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_order_book1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_orders_finalorder1_idx` (`finalorder_orderID` ASC) VISIBLE,
  CONSTRAINT `fk_order_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `bookstore`.`book` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_finalorder1`
    FOREIGN KEY (`finalorder_orderID`)
    REFERENCES `bookstore`.`finalorder` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
